name: Build and package releases
on:
  release:
    types: [created,edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install latest LTS version of Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install

      - name: "Clean: Staging"
        run: rm -rf build
      - name: "Build: Staging"
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: https://legacy-search.workshop.search.lib.umich.edu/
          REACT_APP_SPECTRUM_BASE_URL: https://legacy-search.workshop.search.lib.umich.edu//spectrum
      - name: "Package: Staging"
        run: tar -C build --transform s/./search/ -czf search-staging.tar.gz .
      - name: "Upload Release Asset: Staging"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: search-staging.tar.gz

      - name: "Clean: Production"
        run: rm -rf build
      - name: "Build: Production"
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: https://search.lib.umich.edu
          REACT_APP_SPECTRUM_BASE_URL: https://search.lib.umich.edu/spectrum
      - name: "Package: Production"
        run: tar -C build --transform s/./search/ -czf search-production.tar.gz .
      - name: "Upload Release Asset: Production"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: search-production.tar.gz

      - name: "Clean: Local"
        run: rm -rf build
      - name: "Build: Local"
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: http://127.0.0.1:3000
          REACT_APP_SPECTRUM_BASE_URL: http://127.0.0.1:3000/spectrum
      - name: "Package: Local"
        run: tar -C build --transform s/./search/ -czf search-local.tar.gz .
      - name: "Upload Release Asset: Local"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: search-local.tar.gz

      - name: "Clean: Origin"
        run: rm -rf build
      - name: "Build: Origin"
        run: npm run build
        env:
          CI: false
      - name: "Package: Origin"
        run: tar -C build --transform s/./search/ -czf search-origin.tar.gz .
      - name: "Upload Release Asset: Origin"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: search-origin.tar.gz
